repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    - id: bandit
      exclude: ^tests/

  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        args: ['.']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--max-line-length", "120"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
        additional_dependencies:
          - toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
      - id: pylint
        args: [
            "--max-attributes", "10",
            "--max-args", "10",
            "--disable", "missing-module-docstring",
            "--disable", "import-error",
            "--disable", "raise-missing-from",
            "--disable", "import-outside-toplevel",
        ]
